### ISSUE TITLE
Create a m-b branch and Alt-Acme-Math-XS-ModuleBuild

### ISSUE THREAD

**Issue by ingydotnet** [ingydotnet/acme-math-xs-pm#2]

**Comment by karenetheridge** [comment]
ugh, IMO supporting MB should be a low priority item. MB use should be actively discouraged.

**Comment by ingydotnet** [comment]
Is this a generally accepted position in the Perl Community? Can you link to something somewhat authorative (so that I can link the same when I have to explain why we didn't support MB :)?

**Comment by jberger** [comment]
Until there is a viable alternative that is not using make (for us mortals) I would encourage mb support.

**Comment by Leont** [comment]
> MB use should be actively discouraged.

It's no longer considered "the successor of ExtUtils::MakeMaker", and we're not pushing newbies to pick it up, but it still has a significant user-base (much more than Module::Install, IME) and I don't see that change in the short or medium term future. It's functional, and maintained enough, and it's bug list is no longer than that of ExtUtils::MakeMaker. The only convincing reason for authors to move away from it is that it's rather slow to install (because sucky tests). Quite frankly when trying to do something unusual it's often still the only choice available.

**Comment by mohawk2** [comment]
@Leont, can you give an idea of the "unusual" things MB enables that EUMM can't handle?

**Comment by Leont** [comment]
> @Leont, can you give an idea of the "unusual" things MB enables that EUMM can't handle?

For example, Alien:: distributions are usually using Module::Build because absolutely nothing EUMM does is helping them, and implementing whatever logic they need is likely to be easier in perl than in make+shell (specially if it has to be portable).

I haven't seen a MakeMaker equivalent of Module::Build::WithXSpp either, for example.

**Comment by ingydotnet** [comment]
Done. Mostly anyway. Definitely working, and has Alt-Acme-Math-XS-ModuleBuild
shipped with it.

My opinion of M:B after this is that it's not so bad. The code turned out
pretty nice and I expect to be very minimal after the next refactoring.

The autostub feature doesn't work with M:B for some reason, but I can probably
fix it, and I'm coming to the view that autostubbing is possibly not the best
practice. (ie The jury is still out on autostub).
